CREATE PROCEDURE [dbo].[ML_N_Telephony_Update] @NumML int,    
    @Number         nvarchar(50),
    @PortNum        nvarchar(50),
    @Lock           nvarchar(25),
    @ExtAccess      nvarchar(50),
    @InAccess       nvarchar(50),
    @BanCallIn      nvarchar(50),
    @UnCallFeed     nvarchar(50),
    @ResNum         nvarchar(50),
    @CodeT          nvarchar(50),
    @AONShar        nvarchar(50),
    @UnCallFeedNum  nvarchar(50),
    @PersNumbering  nvarchar(50),
    @StayLinkExt    nvarchar(50),
    @StayLinkInt    nvarchar(50),
    @Operator       nvarchar(255),
    @NumLineE1      nvarchar(50),
    @AONTun         nvarchar(50),
    @InNumAdd       nvarchar(50),
    @WaitNum        nvarchar(50),
    @TripleLink     nvarchar(50),
    @TripleConfLink nvarchar(50),
    @Note           nvarchar(max),
    @DedNum         nvarchar(max),
    @ListResNum     nvarchar(max),
    @NumInSet       nvarchar(max),
    @NumList       nvarchar(max),
	@SPD_PGI nvarchar(50) = NULL
    
AS

set nocount on 

Update dbo.ML_N_Telephony
Set Number = @Number,
    PortNum = @PortNum,
    Lock = @Lock,
    ExtAccess = @ExtAccess,
    InAccess = @InAccess,
    BanCallIn = @BanCallIn,
    UnCallFeed = @UnCallFeed,
    ResNum = @ResNum,
    CodeT = @CodeT,
    AONShar = @AONShar,
    UnCallFeedNum = @UnCallFeedNum,
    PersNumbering = @PersNumbering,
    StayLinkExt = @StayLinkExt,
    StayLinkInt = @StayLinkInt,
    Operator = @Operator,
    NumLineE1 = @NumLineE1,
    AONTun = @AONTun,
    InNumAdd = @InNumAdd,
    WaitNum = @WaitNum,
    TripleLink = @TripleLink,
    TripleConfLink = @TripleConfLink,
    Note = @Note,
    DedNum = @DedNum,
    ListResNum = @ListResNum,
    NumInSet = @NumInSet,
    NumList = @NumList,
	SPD_PGI=@SPD_PGI
WHERE NumML = @NumML