CREATE PROCEDURE dbo.StoredProcedure1
	/*
	(
	@parameter1 int = 5,
	@parameter2 datatype OUTPUT
	)
	*/
AS
	/* SET NOCOUNT ON */


UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315791'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315792'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315793'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315794'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315795'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315796'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315797'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315798'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315799'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315800'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315801'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315802'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315803'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315804'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315805'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315806'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315807'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315808'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315809'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315810'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315811'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315812'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315813'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315814'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315815'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315816'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315817'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315818'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315819'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315820'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315821'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315822'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315823'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315824'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315825'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315826'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315827'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315828'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315829'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315830'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315831'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315832'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315833'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315834'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315835'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315836'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315837'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315838'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315839'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315840'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315841'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315842'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315843'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315844'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315845'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315846'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='315847'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='315861'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='315861'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='316178'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='316297'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='316777'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='316784'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='316785'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='316997'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='316998'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317006'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317007'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317008'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317010'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317011'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317012'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317013'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317014'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317015'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317017'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317018'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317019'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317020'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317021'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317022'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317023'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317024'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317025'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317027'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317028'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317029'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317030'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317036'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='317041'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317180'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317233'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317280'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317295'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317296'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317297'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317349'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317373'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317437'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317441'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317502'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='317597'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318077'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318078'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318080'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318081'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318082'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318083'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318084'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318085'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318086'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318087'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318088'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318089'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318090'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318091'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318092'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318093'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318094'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318095'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318096'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318097'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318098'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318099'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318100'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318101'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318102'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318104'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318105'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318106'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318162'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318171'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318207'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318236'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318353'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318354'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318355'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318356'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318359'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318360'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318361'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318494'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318498'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318500'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318501'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318503'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318504'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318505'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318506'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318507'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318508'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318514'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318518'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318519'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318522'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318525'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318526'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318527'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318528'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318531'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318532'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318534'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318535'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318536'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318537'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318538'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318539'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318541'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318543'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318544'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318545'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318546'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318547'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318548'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318549'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318550'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318551'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318552'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318553'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318554'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318555'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318556'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318557'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318558'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318559'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318560'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318562'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318563'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318564'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318566'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318567'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318568'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318572'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318573'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318574'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318577'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318578'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318579'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318580'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318620'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318621'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318622'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318623'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318624'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318625'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318628'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318629'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318630'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318631'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318632'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318633'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318634'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318635'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318636'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318637'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318638'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318641'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318642'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318643'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318646'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318647'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318648'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318649'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318650'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318651'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318652'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318653'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318654'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318655'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318656'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318657'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318658'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318659'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318660'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318661'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318662'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318742'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318744'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318756'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318757'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318845'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318846'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318851'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318853'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318859'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318860'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='318861'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318877'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318878'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318886'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318886'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318933'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318934'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318935'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='318944'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319066'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319104'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319167'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319168'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319169'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319170'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319178'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319179'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319180'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319181'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319182'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319183'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319184'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319319'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319319'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319387'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319407'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319425'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319426'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319428'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319429'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319430'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319431'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319447'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319506'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319514'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319517'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319520'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319522'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319523'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319525'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319526'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319527'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319528'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319552'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319560'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319579'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319579'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319690'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319691'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319692'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319693'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319694'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319695'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319696'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319697'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319698'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319699'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319700'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319701'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319702'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319703'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319704'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319705'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319706'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319707'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319708'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319709'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319710'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319711'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319736'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319737'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319738'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319739'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319740'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319741'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319742'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319749'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319750'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319751'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319752'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319753'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319766'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319767'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319770'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319772'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319774'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319776'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319779'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319781'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319782'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319788'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319789'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319790'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319791'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319792'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319793'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319794'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319795'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319821'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319826'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319885'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319886'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319887'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319888'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319889'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319890'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319891'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319892'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319894'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319895'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319896'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319897'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319898'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319899'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319900'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319901'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319902'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319903'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319905'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319906'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319907'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='319915'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319953'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319954'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319955'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319956'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319957'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319960'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319963'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319964'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319965'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319966'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319968'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319970'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319972'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319973'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319974'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319975'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319976'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='319995'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='320004'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='320015'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320076'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320085'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='320385'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='320386'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='320387'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320397'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320424'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320443'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320446'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320447'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320448'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320449'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320452'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320470'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320472'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320474'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320595'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='320621'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321054'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321055'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321122'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321150'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321155'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321181'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321182'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321183'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321184'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321185'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321186'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321187'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321188'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321219'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321220'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321221'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321223'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321224'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321225'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321241'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321243'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321255'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321257'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321302'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321336'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321385'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321390'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321391'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321393'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321394'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321401'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321402'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321427'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321463'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321519'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='321590'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='321591'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321639'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321650'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321656'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321730'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321738'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321740'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321743'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321765'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321791'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321810'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321811'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321812'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321813'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='321920'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322040'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322094'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='322171'
UPDATE Main_Table SET Main_Table.spec_project='Спец.проект КР' WHERE Main_Table.NoML_Vkl='322173'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322204'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322216'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322330'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='322400'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322411'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322468'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322518'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322522'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322524'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322532'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322542'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322543'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322546'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322547'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322548'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322550'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322552'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322553'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322560'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322562'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322563'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322565'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322566'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322567'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322568'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322569'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322574'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322592'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322594'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322595'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322596'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322601'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322603'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322606'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322607'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322632'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322678'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322708'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322726'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322726'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322772'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='322896'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323095'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323098'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323103'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323104'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323115'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323116'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323117'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323118'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323121'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323123'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323139'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323160'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323206'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323207'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323251'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323254'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323267'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2009' WHERE Main_Table.NoML_Vkl='323280'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323292'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323292'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323307'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323442'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323517'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323518'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323530'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2009' WHERE Main_Table.NoML_Vkl='323573'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323605'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323620'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323622'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323635'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323637'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323639'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323640'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323642'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323643'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323780'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323849'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323854'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323881'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323883'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323884'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323886'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323887'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323888'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323889'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323892'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323893'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='323962'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324057'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324163'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324176'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324192'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324644'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324694'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324721'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324721'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324722'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324771'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324780'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324789'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324850'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324851'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324907'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324949'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='324950'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325046'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325048'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325072'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325073'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325103'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2009' WHERE Main_Table.NoML_Vkl='325258'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325264'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325267'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325375'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325438'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325506'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325547'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325548'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325549'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325550'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325551'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325552'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325553'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325554'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325555'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325556'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325557'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325559'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325560'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325561'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325562'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325563'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325564'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325565'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325566'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325567'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325568'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325569'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325570'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325571'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325572'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325573'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325574'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325575'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325581'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325609'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325617'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325627'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325637'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325640'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325645'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325653'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325654'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325655'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325658'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325679'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325683'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325687'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325690'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325821'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325828'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325833'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325834'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325836'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325837'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325852'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325856'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325876'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325877'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325878'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325881'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325914'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325915'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325917'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325921'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325923'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325924'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325926'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325927'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325928'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2011' WHERE Main_Table.NoML_Vkl='325930'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325931'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325933'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='325948'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326020'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326046'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326100'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326122'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326172'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326174'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326175'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326176'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326177'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326178'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326179'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326180'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326182'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326183'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326190'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326191'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326192'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326254'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326256'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326257'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326258'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326261'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326262'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326263'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326265'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326266'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326267'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326268'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326273'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326274'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326275'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326278'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326280'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326282'
UPDATE Main_Table SET Main_Table.spec_project='Спец. проект' WHERE Main_Table.NoML_Vkl='326295'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326301'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326307'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326309'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326309'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326311'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326327'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326329'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326330'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326332'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326333'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326336'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326339'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326349'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326350'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326351'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326372'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326431'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326438'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326439'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326440'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326441'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326442'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326443'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326445'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326446'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326447'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326448'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326449'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326485'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326506'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326537'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326549'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326574'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326575'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326604'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326604'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326610'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326655'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326675'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326761'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326837'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='326853'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='327038'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='327056'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='327057'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='327058'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='327064'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='327065'
UPDATE Main_Table SET Main_Table.spec_project='Горзаказ2012' WHERE Main_Table.NoML_Vkl='327066'
	RETURN
