CREATE TABLE [dbo].[CONNECTION_NOTE_EQUIPMENT] (
    [ID]   INT            NOT NULL,
    [NAME] NVARCHAR (128) NULL,
    CONSTRAINT [PK_CONNECTION_NOTE_EQUIPMENT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

