CREATE TABLE [dbo].[FIO] (
    [FIO1]    NVARCHAR (50)    NOT NULL,
    [rowguid] UNIQUEIDENTIFIER CONSTRAINT [DF__FIO__rowguid__70099B30] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    CONSTRAINT [aaaaaFIO_PK] PRIMARY KEY NONCLUSTERED ([FIO1] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [index_1557580587]
    ON [dbo].[FIO]([rowguid] ASC);

