CREATE TABLE [dbo].[ML_Main] (
    [NumMl]           INT            NOT NULL,
    [Nom_Kan]         NVARCHAR (50)  NULL,
    [EqNum]           NVARCHAR (50)  NULL,
    [Usluga]          NVARCHAR (255) NULL,
    [Pre_Usluga]      NVARCHAR (50)  NULL,
    [Zakazchik]       NVARCHAR (255) NULL,
    [Manager]         NVARCHAR (30)  NULL,
    [Telefon]         NVARCHAR (11)  NULL,
    [Osnovanie]       NVARCHAR (255) NULL,
    [Kontakt_Ob]      NVARCHAR (255) NULL,
    [Kol_vo_kan]      NVARCHAR (50)  NULL,
    [Skorost]         NVARCHAR (15)  NULL,
    [QoS]             NVARCHAR (25)  NULL,
    [Klient]          NVARCHAR (15)  NULL,
    [Srochnost]       NVARCHAR (21)  NULL,
    [Data_utv]        NVARCHAR (50)  NULL,
    [Otvetstv_ULSS]   NVARCHAR (100) NULL,
    [Data_ULSS]       NVARCHAR (50)  NULL,
    [Kabel_prov]      NVARCHAR (255) NULL,
    [IP_Adres1]       NVARCHAR (100) NULL,
    [IP_Adres2]       NVARCHAR (100) NULL,
    [Maska1]          NVARCHAR (100) NULL,
    [Maska2]          NVARCHAR (100) NULL,
    [SignalFormat]    NVARCHAR (50)  NULL,
    [NumberRetrans]   INT            NULL,
    [Data_Otkl]       NVARCHAR (25)  NULL,
    [Chanal_Type]     NVARCHAR (25)  NULL,
    [DNS]             NVARCHAR (100) NULL,
    [Shluz]           NVARCHAR (100) NULL,
    [excel]           IMAGE          NULL,
    [excel1]          IMAGE          NULL,
    [PortMMTSNum]     VARCHAR (32)   NULL,
    [commutator_id]   NVARCHAR (128) NULL,
    [commutator_port] NVARCHAR (128) NULL,
    CONSTRAINT [PK__ML_N__53433F50] PRIMARY KEY NONCLUSTERED ([NumMl] ASC)
);

