CREATE TABLE [dbo].[Osnova_ForInserting] (
    [NumML]           INT              NOT NULL,
    [Pre_Usluga]      NVARCHAR (25)    NULL,
    [Usluga]          NVARCHAR (125)   NULL,
    [Nom_Kan]         NVARCHAR (50)    NULL,
    [Zakazchik]       NVARCHAR (255)   NULL,
    [Manager]         NVARCHAR (30)    NULL,
    [Telefon]         NVARCHAR (11)    NULL,
    [Osnovanie]       NVARCHAR (255)   NULL,
    [Kontakt_Ob]      NVARCHAR (255)   NULL,
    [Skorost]         NVARCHAR (30)    NULL,
    [Kol_vo_kan]      NVARCHAR (50)    NULL,
    [Klient]          NVARCHAR (15)    NULL,
    [Srochnost]       NVARCHAR (21)    NULL,
    [Styk_A]          NVARCHAR (32)    NULL,
    [Styk_A1]         NVARCHAR (15)    NULL,
    [Status_StykA]    NVARCHAR (15)    NULL,
    [Line_PrivA]      NVARCHAR (50)    NULL,
    [Adres_A]         NVARCHAR (255)   NULL,
    [Kontakt_A]       NVARCHAR (255)   NULL,
    [Dop_A]           NVARCHAR (512)   NULL,
    [Styk_B]          NVARCHAR (32)    NULL,
    [Styk_B1]         NVARCHAR (15)    NULL,
    [Status_StykB]    NVARCHAR (15)    NULL,
    [Line_PrivB]      NVARCHAR (6)     NULL,
    [Adres_B]         NVARCHAR (255)   NULL,
    [Kontakt_B]       NVARCHAR (255)   NULL,
    [Dop_B]           NVARCHAR (512)   NULL,
    [Utverzh_M]       DATETIME         NULL,
    [Utverzh_B]       DATETIME         NULL,
    [Pr_ULKS]         BIT              NULL,
    [Pr_USP]          BIT              NULL,
    [Pr_UUK]          BIT              NULL,
    [Pr_UPK]          BIT              NULL,
    [Pr_USHKm]        BIT              NULL,
    [Pr_USHKn]        BIT              NULL,
    [Kodir_Usl]       NVARCHAR (10)    NULL,
    [Pr_Obr]          BIT              NULL,
    [town1]           NVARCHAR (150)   NULL,
    [Street1]         NVARCHAR (150)   NULL,
    [Dom1]            NVARCHAR (10)    NULL,
    [Str1]            NVARCHAR (120)   NULL,
    [Kor1]            NVARCHAR (120)   NULL,
    [flow1]           NVARCHAR (150)   NULL,
    [romm1]           NVARCHAR (150)   NULL,
    [town2]           NVARCHAR (150)   NULL,
    [Street2]         NVARCHAR (150)   NULL,
    [Dom2]            NVARCHAR (10)    NULL,
    [Str2]            NVARCHAR (120)   NULL,
    [Kor2]            NVARCHAR (120)   NULL,
    [flow2]           NVARCHAR (150)   NULL,
    [romm2]           NVARCHAR (150)   NULL,
    [Otv_k_utv]       NVARCHAR (250)   NULL,
    [rowguid]         UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL,
    [dateConfirmAct]  DATETIME         NULL,
    [dateLotusAct]    DATETIME         NULL,
    [numberLotusAct]  INT              NULL,
    [signB1]          BIT              NULL,
    [signB2]          BIT              NULL,
    [signB3]          BIT              NULL,
    [signI1]          INT              NULL,
    [signI2]          INT              NULL,
    [signI3]          INT              NULL,
    [signC1]          CHAR (100)       NULL,
    [signC2]          CHAR (1024)      NULL,
    [signC3]          CHAR (100)       NULL,
    [signD1]          DATETIME         NULL,
    [signD2]          DATETIME         NULL,
    [signD3]          DATETIME         NULL,
    [N_eto_StA]       INT              NULL,
    [N_eto_StB]       INT              NULL,
    [ParamStyk1]      NVARCHAR (25)    NULL,
    [ParamStyk2]      NVARCHAR (25)    NULL,
    [QoS]             NVARCHAR (25)    NULL,
    [List2TS]         DATETIME         NULL,
    [ETO_num]         INT              NULL,
    [LS_TU_num]       INT              NULL,
    [project_manager] NVARCHAR (30)    NULL,
    [SpecProject]     NVARCHAR (128)   NULL,
    [Adres_A_old]     NVARCHAR (255)   NULL,
    [Adres_B_old]     NVARCHAR (255)   NULL,
    [ChangeAddr]      NVARCHAR (128)   NULL,
    [AdresA_Old]      NVARCHAR (255)   NULL,
    [AdresB_Old]      NVARCHAR (255)   NULL,
    [BridgeId]        INT              NULL,
    [Marking]         NVARCHAR (255)   NULL,
    [BridgeId_B]      INT              NULL,
    [Marking_B]       NVARCHAR (255)   NULL
);

