CREATE TABLE [dbo].[Sp_FIO] (
    [FIO]     NVARCHAR (50)    NOT NULL,
    [rowguid] UNIQUEIDENTIFIER CONSTRAINT [DF__Sp_FIO__rowguid__2B5F6B28] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    CONSTRAINT [aaaaaSp_FIO_PK] PRIMARY KEY NONCLUSTERED ([FIO] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [index_1426104121]
    ON [dbo].[Sp_FIO]([rowguid] ASC);

