CREATE TABLE [dbo].[UltOsnovaMLPrimExt] (
    [NumML]            INT             NOT NULL,
    [CLIENT]           NVARCHAR (255)  NULL,
    [CUST]             NVARCHAR (255)  NULL,
    [RESP]             NVARCHAR (255)  NULL,
    [N1_OPERATOR]      BIT             NULL,
    [N1_OPERATOR_NAME] NVARCHAR (255)  NULL,
    [N1_OWN]           NVARCHAR (50)   NULL,
    [N1_ADDINFO]       NVARCHAR (2048) NULL,
    [N1_PORT]          NVARCHAR (100)  NULL,
    [N2_OPERATOR]      BIT             NULL,
    [N2_OPERATOR_NAME] NVARCHAR (255)  NULL,
    [N2_OWN]           NVARCHAR (50)   NULL,
    [N2_ADDINFO]       NVARCHAR (2048) NULL,
    [N2_PORT]          NVARCHAR (100)  NULL,
    [ETO_NUM]          NVARCHAR (100)  NULL,
    [N1_OLD_CONTACT]   NVARCHAR (255)  NULL,
    [N2_OLD_CONTACT]   NVARCHAR (255)  NULL,
    [VPN]              BIT             NULL,
    [ADSL_PHONES]      NVARCHAR (255)  NULL,
    [PHONE_OWNER]      NVARCHAR (255)  NULL,
    [MGTS_PHONE]       NVARCHAR (50)   NULL,
    [CHAN_TYPE]        NVARCHAR (50)   NULL,
    [IP_ADDRESSES]     NVARCHAR (255)  NULL,
    [RENT_DATE]        NVARCHAR (100)  NULL,
    [CONN_TYPE]        NVARCHAR (50)   NULL,
    CONSTRAINT [PK_UltOsnovaMLPrimExt] PRIMARY KEY CLUSTERED ([NumML] ASC),
    CONSTRAINT [FK_UltOsnovaMLPrimExt_Osnova] FOREIGN KEY ([NumML]) REFERENCES [dbo].[Osnova] ([NumML]),
    CONSTRAINT [IX_UltOsnovaMLPrimExt] UNIQUE NONCLUSTERED ([NumML] ASC)
);

